Khan/internal-webserver

- gae_dashboard/dos_alert.py
Fix the DOS alerts to ignore 308 redirects, which should be handled by
Fastly and not hit our servers.
Issue: none
Run script and make sure it no longer has the current alert spam
> Fix DOS Alerts

- gae_dashboard/dos_alert.py
- gae_dashboard/waf_alert.py
In cases where there are no blocked requests, the query will return a table with all column values as '(None)'. This PR mainly handles this edge case and will exit the program instead of throwing a type error as it did previously. It also includes documentation and variable naming fixes.
- Find a date and time where there is a query returning 'None' and ensure that no error comes and that nothing shows up on the Slack bot-testing channel. An example is `python waf_alert.py --datetime '2021-07-23 10:03:00'`
- Find a date and time where there is a query that returns a valid output (i.e. '2021-07-28 16:30:00') and ensure that an alert message comes on the bot-testing Slack channel. An example is `python waf_alert.py --datetime '2021-07-28 16:30:00'`
> Fixed empty query, changed datetime arg

- gae_dashboard/dos_alert.py
- gae_dashboard/waf_alert.py
This feature branch from PR #10 includes the following changes:
- Ensures that the correct logs are fetched if the --endtime arg is specified (previously, it was fetching the current date despite the arg being specified)
- Simplified the query to only fetch the max percentage within the 5 minutes
- Alerts the slack channel if the percentage is above a certain threshold SPIKE_PERCENTAGE. This threshold was created from [WAF Investigation](https://app.mode.com/editor/khanacademy/reports/f58d1ec83e48)
- Manually run the query for a time range where the alert > SPIKE_ALERT. For example, '2021-08-02 11:32:00' - '2021-08-02 11:36:59' and note the max ratio returned.
- Run waf_alert.py with the --endtime arg as the end time. 'python waf_alert.py --endtime '2021-08-02 11:37:00'' …
> Alerts when spike detected

- gae_dashboard/waf_alert.py
This script does a very simplistic check for WAF attack and notifies us via
slack if it notices anything that looks like a WAF attack.
- Fixed query to ensure that we only look at fields where blocked=1
- Asserted date to only accept dates after 07/20/21
- Cleaned up alert message
- Formatting to ka-lint standards
- Added commentary for SPIKE_PERCENTAGE
For the negative case:
Manually run the query for a time range where the alert > SPIKE_ALERT. For example, '2021-08-02 11:32:00' - '2021-08-02 11:37:00' and note the max ratio returned.
Run waf_alert.py with the --endtime arg as the end time. 'python waf_alert.py --endtime '2021-08-02 11:37:00'' and ensure that no alert message is sent.
For the positive case:
Manually run the query for a time range where the alert < …
> Added waf_alert.py

- gae_dashboard/sailthru_campaign_export_schema.json
Sailthru is sending us a new field during the campaign export which we need to add to our config for BQ to accept.
Issue: MP-3299
- n/a, config update. verify the job succeeds tomorrow
> Added new field to sailthru_campaign_export_schema.json

- gae_dashboard/waf_alert.py
Originally when we set up with WAF blocking alert we were worried
about the WAF blocking legit traffic and wanted to be alerted so that
we could validate the the traffic was actually bad.
At this point we have a fair amount of confidence in the WAF blocking
bad traffic and so the alert is currently not useful.
This change makes the alert much less sensitive. Now it will only notify
us if significant traffic is being blocked by the WAF. In these cases
we might want to take additional action such as talk with security folks
or implement an IP block.
I set the threshold to 1% which is a guess of where we might want
it. I looked at a bunch of historical alerts and they were are in the
neighbourhood of 0.1% so this threshold should reduce noise. In terms
of whether 1% is the right amount at …
> Make WAF alert less noisy.

- gae_dashboard/dos_alert.py
We've seen this alert trigger for backfills before, and it's happening
again today.
https://khanacademy.slack.com/archives/C8XGW76FQ/p1639597513463100
This change tries to keep the alert from triggering on backfills.  I
use a naive approach which is looking for graphql queries whose name
begins with 'backfill'. Hopefully this catches most of them.
Issue: none
- `python dos_alert.py` to make sure that there are no syntax errors.
> Don't trigger the DoS alert for backfills.

- gae_dashboard/dos_alert.py
For the DoS alert, we were showing IP address info for all IPs, even if
they were only hitting safelisted routes. This only mattered if there
was also an IP hitting a non-safelist route, in which case we would show
an alert with the IP information of all IPs in our Slack alert, which is
confusing.
Now we only print it once for each IP addess only after we know it is
hitting a non-safelisted route.
Issue: https://khanacademy.atlassian.net/browse/INFRA-7341
Run `python ./gae_dashboard/dos_alert.py`
Make sure the script runs and doesn't crash
Deploy and wait until a DoS spike to check and make sure this is fixed
> Stop Showing IP Info for Safelist only IPs

- fastly_notifier.py
This is happening when we test new services.
Issue: email
flake8 fastly_notifier.py
But mostly fingers crossed.
> Allow fastly services to have 0 active versions.

- gae_dashboard/sailthru_campaign_export_schema.json
`local_day` is now being sent to us from sailthru during one of the blast exports. We need to "allow-list" that field to stop the export from failing
Slack Thread: https://khanacademy.slack.com/archives/C8BFYFQ4C/p1645386972799869
Issue: MP-3435
- n/a
> [🔥AUDIT🔥] Adding local_day to sailthru_campaign_export_schema.json

- gae_dashboard/sailthru_campaign_export_schema.json
The sailthru_to_bigquery.py job is failing again due to another var being passed in which we must now allow-list. The error in the log is `No such field: local_time`. Adding this field to sailthru_campaign_export_schema.json will stop this error from happening.
Issue: None
- let it run tomorrow, verify no errors
> [🔥AUDIT🔥] Add local_time to sailthru_campaign_export_schema.json

- gae_dashboard/check_failing_routes.py
- gae_dashboard/dos_alert.py
Filter out noise of a few alerts that we are seeing in the channel.
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1647537266324159?thread_ts=1647518408.605169&cid=C8XGW76FQ
- Run manually and confirm alerts are filtered.
```
$ python check_failing_routes.py --dry-run
No routes with no 2xx requests for 03/16/22
```
> Tidy up noisy non-actionable alerts

- gae_dashboard/email_bq_data.py
If we log a message like `404`, then bq will report it as an int even
though log-messages are in the schema as strings.  Oh well, we just
handle it.  Only one place in our script cares.
Issue: https://groups.google.com/a/khanacademy.org/g/toby-admin/c/W4UemEazMLQ
Fingers crossed for tomorrow's run!
> [🔥AUDIT🔥] Fix email_bq_data for loglines that are just numbers.

- gae_dashboard/dos_alert.py
This mutation is now being rate limited. See
https://khanacademy.atlassian.net/browse/INFRA-6636 However we can't
detect this kind of rate limiting via the fastly logs since rate
limited graphql requests still have 200 reponse codes, not 429.
One solution would be to change the query to join the fastly table
with the request logs and look for particular logged errors in the
requests logs. I'm not sure if this would work very well - since it
would require rate limiting to log a consistent identifiable error,
and it we'd have to be sure about whether any such error in any
service that shares the traceid would be sufficient to indicate that
the request was rate-limited.
Instead I'm approaching things in a more simplistic way that requires
manual labor - safelisting the mutation.
If we end up …
> Exclude login requests from triggering DoS alert.

- gae_dashboard/dos_alert.py
A new Backfill call is triggering our DoS alert.  Adding to the regex to
capture our new convention.
Issue: none
- deploy and validate
> [🔥AUDIT🔥] Relax safelist for backfilling graphql calls

- gae_dashboard/side_by_side_slack_reports.py
This can happen if there are no side-by-side experiments currently in
progress.  That's not an error.
Issue: toby-admin email
> Don't error out if there's no side-by-side bigquery table.

- gae_dashboard/side_by_side_slack_reports.py
It turns out there's a newline in the error text (that slack was eliding):
```
(pdb) p str(e)
"-- Query failed after 2 retries: BigQuery error in query operation: Error processing job\n'khanacademy.org:deductive-jet-827:bq_util_1672935492632373784':\nkhanacademy.org:deductive-jet-827:side_by_side.side_by_side_result_* does not\nmatch any table.\n --"
```
Issue: toby mail
> [🔥AUDIT🔥] Fix the exception-check.

- gae_dashboard/dos_alert.py
Revert "[🔥AUDIT🔥] Change stance of GCP related alerts (#40)"
We have fixed the routing in
https://github.com/Khan/khanflow-pipelines/pull/875 so let's revert this
change.
This reverts commit 67aea3a28f4b292252d94ee2b6f54f0e1a13c970
Issue: XXX-XXXX
n/a
> [🔥AUDIT🔥] Revert "[🔥AUDIT🔥] Change stance of GCP related alerts (#40)"

- gae_dashboard/dos_alert.py
- gae_dashboard/waf_alert.py
WAF and DOS alerts are currently sent to #infrastructure-sre, but security team typically handles the alerts that come in. Based on discussion, there is a preference to move these alerts to #security-engineering.
Context: https://khanacademy.slack.com/archives/C8XGW76FQ/p1682830809828029
Issue: none
> Send WAF and DOS alerts to security Slack channel

- gae_dashboard/initiatives.py
I also got rid of the code that reads the slack channel from the
ownership.json file, since it's not used anymore.
Issues: https://khanacademy.slack.com/archives/C02NMB1R5/p1680195742353999
Issue: INFRA-XXXX
None
> Update the list of team names based on our latest reorg.

- gae_dashboard/check_failing_routes.py
Ignoring known failing routes `/graphql/isActivityAccessibleForProfiles` and `/graphql/isSatStudent`.
They have been triaged to not be a concern, but they are spamming #infrastructure-sre: https://khanacademy.slack.com/archives/C8XGW76FQ/p1686571207671069
They should ideally be fixed, but are temporarily being placed on the ignore list.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9293
SSH'd into Toby:
```
ubuntu@toby:~/internal-webserver$ python gae_dashboard/check_failing_routes.py --dry-run --date 20230611
Routes with no 2xx requests for 06/11/23:
`/graphql/isActivityAccessibleForProfiles` owned by unknown (65 requests total, 44 of them bots, 62 unique IPs)
`/graphql/isSatStudent` owned by unknown (53 requests total, 48 of them bots, 49 unique IPs) …
```
> Ignoring known failing routes.

- gae_dashboard/check_failing_routes.py
Disable alerts for HEAD requests. We expect that all HEAD requests will fail, so no point alerting that they are.
Additionally fixing broken regexes. In testing, a noisy route (`/graphql/getUrgentBanner`) was discovered. Added that to the ignore list but will follow up on that separately.
Issue: none
- SSH into Toby (`gcloud --project=khan-internal-services compute ssh 
ubuntu@toby-internal-webserver --zone=us-central1-c`)
- `cd internal-webserver/`
- `python gae_dashboard/check_failing_routes.py --date=20231205 --dry-run`
- verify failing routes with [HEAD]
- `git checkout ignore-head-requests`
- `python gae_dashboard/check_failing_routes.py --date=20231205 --dry-run`
- verify no failing routes
> Ignoring HEAD requests.

- gae_dashboard/initiatives.py
This now matches the list of active teams and deprecated teams.  There
are even a couple of teams here that I get to remove, because they're
not longer in ownership_data.json! (according to grep.)
Issue: email_bq_data.py log spam
Subscribers: @jvoll
> Get TEAM_EMAIL up to date with ownership.py again.

- gae_dashboard/check_failing_routes.py
Denylist `'/graphql/AuthCookieMutation'` and `/graphql/authcookiemutation` from failing routes alerting. Discussion was held about this route, but I will summarize below: 
https://khanacademy.slack.com/archives/C8XGW76FQ/p1716984015607259
We were initially worried about this because `AuthCookieMutation` is important, as it is used to refresh our KAAL cookie (see more on KA cookies at 
https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/1836613821/Authentication+and+cookies+in+webapp). However, the mutation is a POST, whereas the alert we're receiving is for a GET. On May 28, we saw 1,233 requests for 
`'/graphql/AuthCookieMutation'`, 69 requests for `/graphql/authcookiemutation`, and almost 31 million for `/graphql/AuthCookieMutation [POST]`. Query for more cookie requests here: …
> Silence alerts for AuthCookieMutation GET failures.

- gae_dashboard/initiatives.py
As per the documentation linked on the follow line, KA has
(https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/2774138913/EXAMPLE+New+Team+setup+checklist#Code)
a number of steps required to create a new team. This
is one of those steps.
The README here says this is deprecated but also that "A
lot of things still live here". So, I'm making this update
anyway - perhaps its one of the things still living here.
Issue: none
N/A
> Adding Security as a team in KA
