- gae_dashboard/waf_alert.py
This script does a very simplistic check for WAF attack and notifies us via
slack if it notices anything that looks like a WAF attack.
Run 'python waf_alert.py' and see if there is the appropriate test alert message in the bot-testing Slack channel.
> Added waf_alert.py

- gae_dashboard/Pipfile
- gae_dashboard/Pipfile.lock
- gae_dashboard/README.md
- gae_dashboard/waf_alert.py
Added README to gae_dashboard
Added Pipfile and Pipefile.lock to make setup easier for future.
Proofread the readme, follow the commands for setup
> Added Pipfile and README to gae_dashboard

- gae_dashboard/dos_alert.py
We are getting noise from the DOS alert with this route.
Adding to safelist for now.
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1633384347494400?thread_ts=1633383959.494200&cid=C8XGW76FQ
Deploy and 🤞
> [Audit] Filter `debugDatastoreMapMutation` mutations

- gae_dashboard/dos_alert.py
Adding a currently running backfill to DoS filters.
Also includes some DEI improvements
Issue: none
Test plan:
Deploy and wait for the DoS script to run
> Add Running Backfill to DoS Filters

- gae_dashboard/dos_alert.py
We tempoarily disable the alert while we deal with ratelimiting the
alert.
Issue: 6713
I'm going to deploy this while this is reviewed.
> Add getUserProfile endpoint to safelist

- fastly_notifier.py
That's what I get for using an untyped language...
Issue: email
> [🔥AUDIT🔥] Have the default `active_version` object be of the right type.

- gae_dashboard/dos_alert.py
Accomodating for a new graphql ops (`syncEduOrganizations`).  These are validated by our graphql
safelist so we are only filtering on prefix here to avoid toil.
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1651518122031889?thread_ts=1651517598.725849&cid=C8XGW76FQ
- Deploy and check
> [🔥AUDIT🔥] Extend safelist for dos alert

- gae_dashboard/dos_alert.py
Adding `phantomDeletion` and Learning Equality API use to our backfill safelist to avoid noise on alert.
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1668029412887979
Test plan:
none
> Safelist phantomDeletion and Learning Equality

- gae_dashboard/dos_alert.py
These routes minimal impact and we use these internally.
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1668805072413439?thread_ts=1668804312.182019&cid=C8XGW76FQ
(none)
> [🔥AUDIT🔥] Added /_fastly routes to safelist

- gae_dashboard/dos_alert.py
> note: this is an open repo
Due to recent change of khanflow [1], most of our khanflow map entities job
will now go through Fastly and trigger alert.
As a temporary long weekend solution, we avoid alerting GCP (specifically GCE due to
the bc subdomain check) for now.  This have an obvious issue that we will skip 
DOS source from GCP, but we have not seen that IRL, and we have other lines of defense.  A long term solution is to make
khanflow have better way to skip our alert monitoring.
[1] https://github.com/Khan/khanflow-pipelines/commit/0c28050020329506ae521ccf674e13d0d6892091
Issue: https://khanacademy.slack.com/archives/C8XGW76FQ/p1676597711023059
- I will deploy this for now and hope it stop the noise
> [🔥AUDIT🔥] Change stance of GCP related alerts

- gae_dashboard/dos_alert.py
This change converts the list of URL regexes into a dictionary, which allows us to set values higher than the default max number of requests on a per-URL-regex basis. Some routes, such as `/_fastly` routes, can have multiple automated requests from our own code, and while we don't want to entirely ignore them, being able to adjust the threshold upon which they alert will reduce the number of false alarms.
This change also sets `/_fastly` and `/_api/static_version` requests to 10x the default alerting threshold, or 100 requests per second vs the default of 10.
> Allow overriding max requests to alert on

- gae_dashboard/dos_alert.py
Also improve a comment's readability!
> Fix reference before definition bug in dos_alert

- README
The commands didn't work as written for me, I probably have my default zone set that I should fix. However, I don't think it can hurt to be more precise with our commands.
Issue: none
Executed the command as written now and confirmed successful SSH session.
> Adding zone flag to README commands.

- download_jenkins_perf_data.sh
We upload it to a public gcs bucket!
Issue: none
None
> [🔥AUDIT🔥] Say how to access the perf data after generating it.

- gae_dashboard/README.md
We're porting all our secrets from Keeper to GSM, and we need to
change our documentation (and code!) to match.  This is part of that
effort.
Issue: https://khanacademy.atlassian.net/browse/INFRA-9448
None
> [🔥AUDIT🔥] Replace references to Keeper with references to Google Secrets Manager.

- khantube-oauth-collector/secrets_example.py
This way, we can remove the secrets from secrets.py, which doesn't
otherwise need them.
Issue: none
None
> [🔥AUDIT🔥] Document how to get secrets from GSM, not from secrets.py.

- update_github_teams.py
I fixed the base64-encoding issue in one place in this file, but not
the other!  I wonder why it just started complaining now.
Issue: emails from phabricator
> [🔥AUDIT🔥] Another bytes vs strings problem.

- gae_dashboard/initiatives.py
This updates the email addresses for LEMS, Literacy, Content Library, and Test Prep per the ticket.
Issue: LIT-779
> Update email addresses for teams under learner experience

- gae_dashboard/initiatives.py
Adding the assessments team everywhere.
https://khanacademy.atlassian.net/wiki/spaces/Assessment/pages/2938634241/Assessments+Team+Setup
Issue: AX-7
none
> Add the assessments team

- gae_dashboard/initiatives.py
I hope that all our repos have been rewritten to use the new team
names!  The TODO says it's safe to remove now, so we'll see...
Issue: none
> Remove obsolete teams from our list of teams.
